23 file verification
q6-enterprises-inc/fluture-remote-file-manager pull request #36
Opened 2020-09-28 18:04 UTC by johngoza

2020-09-28 21:47 UTC, mreinigjr requested changes
In the dependency requirement statements, please list the full file name.  Just doing `.../ftp` might get us in trouble vs `.../ftp.js`.

We need to start making these PRs smaller if possible.

2020-09-28 21:47 UTC, mreinigjr commented on lib/sftp.js
>  const sendFileViaSftp =
Here is my suggestion for this function

```const sendFileViaSftp =
    def("sendFileViaSftp")
    ({})
    ([SshClientType, ReadStreamType, SftpConnectionConfig, FutureType($.String)($.String)])
    (client => readStream => connectionConfig => Future((reject, resolve) => {
      client.on("error", (err) => {
        client.end();
        reject(err);
      });

      client.on("ready", () => {
        client.sftp((err, sftp) => {
          if (err) {
            client.end();
            reject(err);
          } else {
            const writeStream = sftp.createWriteStream(connectionConfig.remoteFileName);
            writeStream.on("error", (err) => {
              client.end();
              reject(err);
            });

            writeStream.on("ready", () => {
              readStream.pipe(writeStream);
              resolve("Upload successful");
            });

            writeStream.on("close", () => {
              client.end();
            });
          }
        });
      });

      // todo: probably here too
      client.connect(connectionConfig);
      return () => { };
    }));```

2020-09-28 21:47 UTC, mreinigjr commented on lib/sftp.js
> +      // todo: probably here too
what does this `todo` mean?

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/ftp-tests.js
> +  });
Should this be deleted?

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/ftp-tests.js
> +        expect(err).to.deep.equal("400 Directory not found");
```suggestion
        expect(err).to.equal("400 Directory not found");
```

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/ftp-tests.js
> +      (data => {
you could have just checked that the result was an instance of a readable.  Either that, you should update the description of your test.

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/ftp-tests.js
> +        expect(err).to.deep.equal("500 an error occurred");
```suggestion
        expect(err).to.equal("500 an error occurred");
```

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/ftp-tests.js
> +          expect(result).to.deep.equal("hello world");
```suggestion
          expect(result).to.equal("hello world");
```

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/ftp-tests.js
> +  describe("verifyAndGetFileViaFtp", function() {
`verifyAndGetFileViaFtp` is composition of several functions that are already unit tested.  This particular suite of tests should be in the integration folder.

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/ftp-tests.js
> +        expect(err).to.deep.equal(expectedError);
```suggestion
        expect(err).to.equal(expectedError);
```

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/sftp-tests.js
> +        expect(data).to.deep.equal(mockFileList);
`expect(data).to.deep.equal(mockFileList);` 
:+1:

`deep` should be used on objects that you have.  Sometimes it is funky with arrays though.

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/sftp-tests.js
> +        expect(err).to.deep.equal("400 Directory not found");
```suggestion
        expect(err).to.equal("400 Directory not found");
```

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/sftp-tests.js
> +        expect(data).to.deep.equal(mockSftpClient);
:+1:

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/sftp-tests.js
> +  describe("verifyAndGetFileViaSftp", function() {
should also live in integration test folder

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/sftp-tests.js
> +  describe("verifyFile", function() {
this too should be in integration test folder

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/utility-functions-tests.js
> +  describe("filterFileMetadata", function() {
Is `filterFileMetadata` really reusable across all 3 channels right now?

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/utility-functions-tests.js
>          "host": "",
`host` is not `null`, but rather an empty string.

So since you are using `R.isNull` and `R.isEmpty`, you will need to have tests for both the empty string and for when it is `null`.

2020-09-28 21:47 UTC, mreinigjr commented on tests/unit/lib/utility-functions-tests.js
> +    it("should reject if remoteFileName is null", function() {
again, you are testing the empty string case and not the null case.

2020-09-29 19:43 UTC, johngoza commented on tests/unit/lib/ftp-tests.js
> +        expect(err).to.deep.equal("400 Directory not found");
deep equal is silly for simple data types; use for nested only. :me: === :dummy:

2020-10-13 15:27 UTC, johngoza commented on tests/unit/lib/utility-functions-tests.js
> +    it("should reject if remoteFileName is null", function() {
![image](https://user-images.githubusercontent.com/6828226/95881949-bcb45380-0d3e-11eb-9382-a45950a37f4a.png)

2020-10-13 15:28 UTC, johngoza commented on tests/unit/lib/utility-functions-tests.js
> +    it("should reject if remoteFileName is null", function() {
not sure why github is being bad here

2020-10-13 15:28 UTC, johngoza commented on tests/unit/lib/utility-functions-tests.js
>          "host": "",
again unsure why github is being bad here

2020-10-16 21:44 UTC, mreinigjr approved these changes

2020-10-16 21:46 UTC, merged